services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_portfolio
    restart: unless-stopped
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    environment:
      MONGO_INITDB_DATABASE: portfolio
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test:
        ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-init:
    image: mongo:latest
    container_name: mongodb_portfolio_init
    depends_on:
      - mongodb
    restart: "no"
    entrypoint: >
      bash -c "
        echo 'Waiting for MongoDB to start...';

        until mongosh --host mongodb:27017 --quiet --eval 'db.adminCommand(\"ping\").ok'; do
          sleep 2;
        done;

        echo 'MongoDB is up. Checking replica set...';

        mongosh --host mongodb:27017 --quiet --eval '
          try {
            rs.status();
            print(\"Replica set already initialized\");
          } catch (err) {
            print(\"Initializing replica set...\");
            rs.initiate({
              _id: \"rs0\",
              members: [
                {
                  _id: 0,
                  host: \"localhost:27017\"
                }
              ]
            });
          }
        ';

        echo 'Replica set init complete.';
      "

volumes:
  mongo_data:
